### ISSUE TITLE
Fatal constructor error in PHP8

### ISSUE THREAD

**Issue by dd32** [WordPress/blogger-importer#1]
As reported on: https://core.trac.wordpress.org/ticket/52084

```
Fatal error: Declaration of WP_SimplePie_Blog_Item::get_id($hash = false) must be compatible with SimplePie_Item::get_id($hash = false, $fn = 'md5') in plugins/blogger-importer/blogger-importer-blogitem.php on line 111
```

Also reported in: https://core.trac.wordpress.org/ticket/49143

**Comment by ironprogrammer** [comment]
Resolved via https://github.com/WordPress/blogger-importer/commit/8c7fef2121815ab479abe427dcbf2116074c645e.
